# This file is managed by the Sonect frontend.
# Browser output mode — MPD plays silently.

audio_output {
    type        "alsa"
    name        "PCH (card 0)"
    device      "hw:0,0"
    mixer_type  "software"
}
# Allow MPD to follow symlinks to local storage folders (managed by Sonect)
follow_outside_symlinks "yes"
