music_directory "/workspace/music"
playlist_directory "/var/lib/mpd/playlists"
db_file "/var/lib/mpd/tag_cache"
state_file "/var/lib/mpd/state"
sticker_file "/var/lib/mpd/sticker.sql"
log_file "/var/lib/mpd/mpd.log"

bind_to_address "0.0.0.0"
port "6600"

# audio_output {
#     type "alsa"
#     name "ALSA Output"
#     mixer_type "none"
# }

audio_output {
    type "null"
    name "Dummy Output"
}
