# This file is managed by the Sonect frontend.
# Browser output mode — MPD plays silently.

audio_output {
    type        "alsa"
    name        "HDMI (card 1)"
    device      "hw:1,7"
    mixer_type  "software"
}
# Allow MPD to follow symlinks to local storage folders (managed by Sonect)
follow_outside_symlinks "yes"
